#   {{{3
#   vim: set tabstop=4 modeline modelines=10:
#   vim: set foldlevel=2 foldcolumn=2 foldmethod=marker:
#   {{{2
import time
from typing import List, Optional

class Solution:
    """Determine the number of bit flips necessary to turn integer `start` into `goal`"""

    #   runtime: beats 92%
    #    memory: beats 69%
    def minBitFlips_Pythonic(self, start: int, goal: int) -> int:
        def int2CharArrays(num1: int, num2: int) -> list:
            """Converts two integers to their binary representations as lists of characters, with the shorter binary representation padded with leading zeros to match the length of the longer one (generated by gpt4o)."""
            b1 = bin(num1)[2:]
            b2 = bin(num2)[2:]
            max_len = max(len(b1), len(b2))
            b1 = b1.zfill(max_len)
            b2 = b2.zfill(max_len)
            return list(b1), list(b2)
        start, goal = int2CharArrays(start, goal)
        result = 0
        for c1, c2 in zip(start, goal):
            if c1 != c2:
                result += 1
        return result


    #   runtime: beats 82%
    #    memory: beats 69%
    def minBitFlips_BitwiseLoop(self, start: int, goal: int) -> int:
        if start == goal: 
            return 0
        a = min(start, goal)
        b = max(start, goal)
        result = 0
        while a > 0 or b > 0:
            if (a & 1) != (b & 1):
                result += 1
            a >>= 1
            b >>= 1
        return result


    #   runtime: beats 99%
    #    memory: beats 94%
    def minBitFlips_BitwiseXorPythonicStrCount(self, start: int, goal: int) -> int:
        return bin(start ^ goal).count('1')
        

    #   runtime: beats 99%
    #    memory: beats 93%
    def minBitFlips_BitwiseXorPythonicBitCount(self, start: int, goal: int) -> int:
        return (start ^ goal).bit_count()


    #   runtime: beats 82%
    #    memory: beats 94%
    def minBitFlips_BitwiseXorKernighan(self, start: int, goal: int) -> int:
        x = start ^ goal
        result = 0
        while x:
            x &= (x - 1)    #   clear lowest bit
            result += 1
        return result


s = Solution()
test_functions = [ s.minBitFlips_Pythonic, s.minBitFlips_BitwiseLoop, s.minBitFlips_BitwiseXorPythonicStrCount, s.minBitFlips_BitwiseXorPythonicBitCount, s.minBitFlips_BitwiseXorKernighan, ]

inputs = [ (10,7), (3,4), (23, 4), (50_000_000_000_000_111, 143_214_905_000_222), ]
checks = [ 3, 3, 3, 29, ]
assert len(inputs) == len(checks), "input/check lists length mismatch"
assert len(inputs) > 0, "No input"

for f in test_functions:
    print(f.__name__)
    start_time = time.time()
    for (start, goal), check in zip(inputs, checks):
        print(f"start=({start}), goal=({goal})")
        result = f(start, goal)
        print(f"result=({result})")
        assert result == check, "Check comparison failed"
    print("elapsed_us=(%0.2f)" % ((time.time() - start_time) * 1_000_000))
    print()

